# Generated by Django 5.2.6 on 2025-09-25 08:55

import django.core.validators
import django.db.models.deletion
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(5000)])),
                ('condition', models.CharField(choices=[('NEW', 'Mới'), ('LIKE_NEW', 'Gần như mới'), ('GOOD', 'Tốt'), ('FAIR', 'Tạm'), ('POOR', 'Kém')], default='GOOD', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ duyệt'), ('PUBLISHED', 'Đã đăng'), ('SOLD', 'Đã bán'), ('ARCHIVED', 'Lưu trữ')], db_index=True, default='DRAFT', max_length=16)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_listings', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.listing_image_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status', 'created_at'], name='listings_li_categor_17faf7_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['slug'], name='listings_li_slug_a2fd83_idx'),
        ),
    ]
