# Generated by Django 5.2.6 on 2025-09-25 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_categor_17faf7_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_price_d6caaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_slug_a2fd83_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Mới'), ('used', 'Đã qua sử dụng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='VND', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('PUBLISHED', 'Đã đăng')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
