# Generated by Django 5.2.6 on 2025-09-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_listing_bb2284_idx',
            old_name='chat_conv_listing_created_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_buyer_i_c3bb8d_idx',
            old_name='chat_conv_buyer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_seller__e74b90_idx',
            old_name='chat_conv_seller_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_msg_conversation_created_idx',
        ),
    ]
